"""connect orders to products

Revision ID: 4a6857b9d109
Revises: 36dc195b5b24
Create Date: 2026-09-07 23:22:38.945374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6857b9d109'
down_revision: Union[str, Sequence[str], None] = '36dc195b5b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['product_id'])
    op.drop_column('orders', 'product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'product_id')
    # ### end Alembic commands ###
